<a href="https://colab.research.google.com/github/pankaj372/ASS.1/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ASSIGNMET

Q.1  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [ ]:
import numpy as np

# Create a NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the array
print("Array:", arr)

# Print the data type of the array
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


Q.2  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np

# Given data
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type of the array is float64
is_float64 = arr.dtype == np.float64

print("Is the array of type float64?", is_float64)


Is the array of type float64? True


Q.3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np

# Create a NumPy array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array
print("Array:", arr)

# Print the data type of the array
print("Data type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


Q.4  Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np

# Example NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Converted array:", arr_float32)

# Print the data type of the converted array
print("Data type:", arr_float32.dtype)


Converted array: [1. 2. 3. 4. 5.]
Data type: float32


Q.5  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np

# Example NumPy array with float64 data type
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Converted array:", arr_float32)

# Print the data type of the converted array
print("Data type:", arr_float32.dtype)


Converted array: [1.1 2.2 3.3 4.4 5.5]
Data type: float32


Q.6 . Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [ ]:
import numpy as np

def array_attributes(arr):
    """
    Function to return the shape, size, and data type of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the shape, size, and data type of the array
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype

    return shape, size, dtype

# Example usage
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])


Shape: (5,)
Size: 5
Data type: float64


Q.7.  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [ ]:
import numpy as np

def array_dimension(arr):
    """
    Function to return the dimensionality of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    int: The dimensionality of the array
    """
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print("Dimensionality:", dimension)


Dimensionality: 2


Q.8  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
import numpy as np

def item_size_info(arr):
    """
    Function to return the item size and the total size in bytes of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the item size and the total size in bytes
    """
    item_size = arr.itemsize
    total_size = arr.nbytes

    return item_size, total_size

# Example usage
arr = np.array([1, 2, 3, 4, 5])
size_info = item_size_info(arr)
print("Item size:", size_info[0], "bytes")
print("Total size:", size_info[1], "bytes")


Item size: 8 bytes
Total size: 40 bytes


Q. 9  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np

def array_strides(arr):
    """
    Function to return the strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the strides of the array
    """
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


Q.10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Function to return the shape and strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the shape and strides of the array
    """
    shape = arr.shape
    strides = arr.strides

    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_strides = shape_stride_relationship(arr)
print("Shape:", shape_strides[0])
print("Strides:", shape_strides[1])


Shape: (2, 3)
Strides: (24, 8)


Q.11  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
import numpy as np

def create_zeros_array(n):
    """
    Function to create a NumPy array of zeros with n elements.

    Parameters:
    n (int): Number of elements in the array

    Returns:
    numpy.ndarray: A NumPy array of zeros with n elements
    """
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)
print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


Q.12  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Function to create a 2D NumPy array filled with ones of size rows x cols.

    Parameters:
    rows (int): Number of rows in the array
    cols (int): Number of columns in the array

    Returns:
    numpy.ndarray: A 2D NumPy array filled with ones of size rows x cols
    """
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Matrix of ones:\n", ones_matrix)


Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q. 13  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Function to create a NumPy array with a range starting from start, ending at stop (exclusive),
    and with the specified step.

    Parameters:
    start (int): The starting value of the range
    stop (int): The end value of the range (exclusive)
    step (int): The step size between consecutive values

    Returns:
    numpy.ndarray: A NumPy array with the specified range
    """
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Range array:", range_array)


Range array: [0 2 4 6 8]


Q.14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).


In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Function to create a NumPy array with num equally spaced values between start and stop (inclusive).

    Parameters:
    start (float): The starting value of the range
    stop (float): The end value of the range
    num (int): The number of equally spaced values to generate

    Returns:
    numpy.ndarray: A NumPy array with the specified range
    """
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


Q.15  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
import numpy as np

def create_identity_matrix(n):
    """
    Function to create a square identity matrix of size n x n.

    Parameters:
    n (int): The size of the identity matrix

    Returns:
    numpy.ndarray: A square identity matrix of size n x n
    """
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q.16  Write a function that takes a Python list and converts it into a NumPy array.


In [ ]:
import numpy as np

def list_to_numpy_array(py_list):
    """
    Function to convert a Python list into a NumPy array.

    Parameters:
    py_list (list): Input Python list

    Returns:
    numpy.ndarray: A NumPy array converted from the input list
    """
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print("NumPy array:", numpy_array)
print("Data type:", type(numpy_array))


NumPy array: [1 2 3 4 5]
Data type: <class 'numpy.ndarray'>


Q. 17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [ ]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new array object with the same data using numpy.view
view_array = original_array.view()

# Print the original array and the view array
print("Original array:", original_array)
print("View array:", view_array)

# Modify the view array
view_array[0] = 10

# Print the arrays after modification
print("Original array after modification:", original_array)
print("View array after modification:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Original array after modification: [10  2  3  4  5]
View array after modification: [10  2  3  4  5]


Q.18  Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [ ]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Function to concatenate two NumPy arrays along a specified axis.

    Parameters:
    arr1 (numpy.ndarray): The first input array
    arr2 (numpy.ndarray): The second input array
    axis (int): The axis along which the arrays will be concatenated (default is 0)

    Returns:
    numpy.ndarray: The concatenated array
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along axis 1 (columns)
concatenated_array_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
