<a href="https://colab.research.google.com/github/pankaj372/ASS.1/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ASSIGNMET

Q.1  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [1]:
import numpy as np

# Create a NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the array
print("Array:", arr)

# Print the data type of the array
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


Q.2  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [2]:
import numpy as np

# Given data
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type of the array is float64
is_float64 = arr.dtype == np.float64

print("Is the array of type float64?", is_float64)


Is the array of type float64? True


Q.3  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
import numpy as np

# Create a NumPy array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array
print("Array:", arr)

# Print the data type of the array
print("Data type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


Q.4  Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
import numpy as np

# Example NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Converted array:", arr_float32)

# Print the data type of the converted array
print("Data type:", arr_float32.dtype)


Converted array: [1. 2. 3. 4. 5.]
Data type: float32


Q.5  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [5]:
import numpy as np

# Example NumPy array with float64 data type
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array
print("Converted array:", arr_float32)

# Print the data type of the converted array
print("Data type:", arr_float32.dtype)


Converted array: [1.1 2.2 3.3 4.4 5.5]
Data type: float32


Q.6 . Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [6]:
import numpy as np

def array_attributes(arr):
    """
    Function to return the shape, size, and data type of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the shape, size, and data type of the array
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype

    return shape, size, dtype

# Example usage
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])


Shape: (5,)
Size: 5
Data type: float64


Q.7.  Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [7]:
import numpy as np

def array_dimension(arr):
    """
    Function to return the dimensionality of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    int: The dimensionality of the array
    """
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print("Dimensionality:", dimension)


Dimensionality: 2


Q.8  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [8]:
import numpy as np

def item_size_info(arr):
    """
    Function to return the item size and the total size in bytes of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the item size and the total size in bytes
    """
    item_size = arr.itemsize
    total_size = arr.nbytes

    return item_size, total_size

# Example usage
arr = np.array([1, 2, 3, 4, 5])
size_info = item_size_info(arr)
print("Item size:", size_info[0], "bytes")
print("Total size:", size_info[1], "bytes")


Item size: 8 bytes
Total size: 40 bytes


Q. 9  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [9]:
import numpy as np

def array_strides(arr):
    """
    Function to return the strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the strides of the array
    """
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)


Strides: (24, 8)


Q.10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [10]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Function to return the shape and strides of a NumPy array.

    Parameters:
    arr (numpy.ndarray): Input NumPy array

    Returns:
    tuple: A tuple containing the shape and strides of the array
    """
    shape = arr.shape
    strides = arr.strides

    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_strides = shape_stride_relationship(arr)
print("Shape:", shape_strides[0])
print("Strides:", shape_strides[1])


Shape: (2, 3)
Strides: (24, 8)


Q.11  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [11]:
import numpy as np

def create_zeros_array(n):
    """
    Function to create a NumPy array of zeros with n elements.

    Parameters:
    n (int): Number of elements in the array

    Returns:
    numpy.ndarray: A NumPy array of zeros with n elements
    """
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)
print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


Q.12  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [12]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Function to create a 2D NumPy array filled with ones of size rows x cols.

    Parameters:
    rows (int): Number of rows in the array
    cols (int): Number of columns in the array

    Returns:
    numpy.ndarray: A 2D NumPy array filled with ones of size rows x cols
    """
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Matrix of ones:\n", ones_matrix)


Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q. 13  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [13]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Function to create a NumPy array with a range starting from start, ending at stop (exclusive),
    and with the specified step.

    Parameters:
    start (int): The starting value of the range
    stop (int): The end value of the range (exclusive)
    step (int): The step size between consecutive values

    Returns:
    numpy.ndarray: A NumPy array with the specified range
    """
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Range array:", range_array)


Range array: [0 2 4 6 8]


Q.14  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).


In [14]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Function to create a NumPy array with num equally spaced values between start and stop (inclusive).

    Parameters:
    start (float): The starting value of the range
    stop (float): The end value of the range
    num (int): The number of equally spaced values to generate

    Returns:
    numpy.ndarray: A NumPy array with the specified range
    """
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


Q.15  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [16]:
import numpy as np

def create_identity_matrix(n):
    """
    Function to create a square identity matrix of size n x n.

    Parameters:
    n (int): The size of the identity matrix

    Returns:
    numpy.ndarray: A square identity matrix of size n x n
    """
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q.16  Write a function that takes a Python list and converts it into a NumPy array.


In [17]:
import numpy as np

def list_to_numpy_array(py_list):
    """
    Function to convert a Python list into a NumPy array.

    Parameters:
    py_list (list): Input Python list

    Returns:
    numpy.ndarray: A NumPy array converted from the input list
    """
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print("NumPy array:", numpy_array)
print("Data type:", type(numpy_array))


NumPy array: [1 2 3 4 5]
Data type: <class 'numpy.ndarray'>


Q. 17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [18]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a new array object with the same data using numpy.view
view_array = original_array.view()

# Print the original array and the view array
print("Original array:", original_array)
print("View array:", view_array)

# Modify the view array
view_array[0] = 10

# Print the arrays after modification
print("Original array after modification:", original_array)
print("View array after modification:", view_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Original array after modification: [10  2  3  4  5]
View array after modification: [10  2  3  4  5]


Q.18  Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [19]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Function to concatenate two NumPy arrays along a specified axis.

    Parameters:
    arr1 (numpy.ndarray): The first input array
    arr2 (numpy.ndarray): The second input array
    axis (int): The axis along which the arrays will be concatenated (default is 0)

    Returns:
    numpy.ndarray: The concatenated array
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_0)

# Concatenate along axis 1 (columns)
concatenated_array_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


Q. 19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [20]:
import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Adjust the shape of arr2 to match the number of rows in arr1 for horizontal concatenation
arr2 = np.hstack((arr2, np.zeros((arr2.shape[0], arr1.shape[1] - arr2.shape[1]))))

# Concatenate the arrays horizontally (along axis 1)
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7.  8.  0.]
 [ 9. 10.  0.]]
Concatenated array:
 [[ 1.  2.  3.  7.  8.  0.]
 [ 4.  5.  6.  9. 10.  0.]]


Q.20 Write a function that vertically stacks multiple NumPy arrays given as a list

In [21]:
import numpy as np

def vertical_stack(arrays):
    """
    Function to vertically stack multiple NumPy arrays given as a list.

    Parameters:
    arrays (list of numpy.ndarray): List of NumPy arrays to be stacked

    Returns:
    numpy.ndarray: A single NumPy array obtained by stacking the input arrays vertically
    """
    return np.vstack(arrays)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

arrays = [arr1, arr2, arr3]
stacked_array = vertical_stack(arrays)
print("Stacked array:\n", stacked_array)


Stacked array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


Q. 21  Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size

In [22]:
import numpy as np

def create_range_array(start, stop, step):
    """
    Function to create a NumPy array of integers within a specified range (inclusive) with a given step size.

    Parameters:
    start (int): The starting value of the range
    stop (int): The end value of the range (inclusive)
    step (int): The step size between consecutive values

    Returns:
    numpy.ndarray: A NumPy array with the specified range
    """
    return np.arange(start, stop + 1, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = create_range_array(start, stop, step)
print("Range array:", range_array)


Range array: [ 0  2  4  6  8 10]


Q. 22  Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [23]:
import numpy as np

def generate_equally_spaced_values():
    """
    Function to generate a NumPy array of 10 equally spaced values between 0 and 1 (inclusive).

    Returns:
    numpy.ndarray: A NumPy array with 10 equally spaced values between 0 and 1
    """
    return np.linspace(0, 1, 10)

# Example usage
equally_spaced_values = generate_equally_spaced_values()
print("Equally spaced values:", equally_spaced_values)


Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q. 23  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [24]:
import numpy as np

def generate_logarithmic_values():
    """
    Function to generate a NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

    Returns:
    numpy.ndarray: A NumPy array with 5 logarithmically spaced values between 1 and 1000
    """
    return np.logspace(0, 3, 5)

# Example usage
logarithmic_values = generate_logarithmic_values()
print("Logarithmically spaced values:", logarithmic_values)


Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


Q. 24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [25]:
import numpy as np
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
np.random.seed(0)  # For reproducibility
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Print the DataFrame
print(df)


   Column1  Column2  Column3
0       45       48       65
1       68       68       10
2       84       22       37
3       88       71       89
4       89       13       59


Q. 25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [27]:
import numpy as np
import pandas as pd

def replace_negatives_with_zeros(df, column_name):
    """
    Function to replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    df (pandas.DataFrame): Input DataFrame
    column_name (str): The name of the column to process

    Returns:
    pandas.DataFrame: DataFrame with negative values replaced by zeros in the specified column
    """
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [1, 2, 3, 4, 5]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

df = replace_negatives_with_zeros(df, 'A')
print("\nDataFrame after replacing negatives in column 'A':\n", df)


Original DataFrame:
    A  B  C
0  1 -1  1
1 -2  2  2
2  3 -3  3
3 -4  4  4
4  5 -5  5

DataFrame after replacing negatives in column 'A':
    A  B  C
0  1 -1  1
1  0  2  2
2  3 -3  3
3  0  4  4
4  5 -5  5


Q. 26 Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])

In [28]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2, since indexing starts from 0)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


Q.27  Retrieve the element at index (1, 2) from the 2D NumPy array. arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
import numpy as np

# Given 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Access the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


Q. 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array  arr = np.array([3, 8, 2, 10, 5, 7])



In [30]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]

print(result)


[ 8 10  7]


Q. 29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.  arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[2:6]

print(result)


[3 4 5 6]


Q. 30 . Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [4, 5, 6, 7],
                [7, 8, 9, 10]])

# Extracting the sub-array
sub_array = arr[0:2, 1:3]

print(sub_array)


Q. 31 .Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [32]:
import numpy as np

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array based on provided indices.

    Parameters:
    arr (np.ndarray): The 2D array to extract elements from.
    indices (np.ndarray): A 2D array of indices.

    Returns:
    np.ndarray: An array of extracted elements.
    """
    return arr[indices[:, 0], indices[:, 1]]

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.array([[0, 1],
                    [1, 2],
                    [2, 0]])

result = extract_elements(arr, indices)
print(result)


[2 6 7]


Q. 32  Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [33]:
import numpy as np

def filter_elements(arr, threshold):
    """
    Filter elements greater than a specified threshold from a 1D array.

    Parameters:
    arr (np.ndarray): The 1D array to filter elements from.
    threshold (float): The threshold value.

    Returns:
    np.ndarray: An array of elements greater than the threshold.
    """
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 4, 6, 8, 3, 7, 2])
threshold = 5
result = filter_elements(arr, threshold)
print(result)


[6 8 7]


Q. 33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [34]:
import numpy as np

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    """
    Extract specific elements from a 3D array using indices provided in three separate arrays.

    Parameters:
    arr (np.ndarray): The 3D array to extract elements from.
    x_indices (np.ndarray): The array of indices for the first dimension.
    y_indices (np.ndarray): The array of indices for the second dimension.
    z_indices (np.ndarray): The array of indices for the third dimension.

    Returns:
    np.ndarray: An array of extracted elements.
    """
    return arr[x_indices, y_indices, z_indices]

# Example usage
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6],
                 [ 7,  8,  9]],

                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]],

                [[19, 20, 21],
                 [22, 23, 24],
                 [25, 26, 27]]])

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 2, 0])
z_indices = np.array([2, 1, 0])

result = extract_elements_3d(arr, x_indices, y_indices, z_indices)
print(result)


[ 6 17 19]


Q. 34  Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [35]:
import numpy as np

def filter_elements(arr, condition1, condition2):
    """
    Filter elements from an array where both conditions are satisfied.

    Parameters:
    arr (np.ndarray): The array to filter elements from.
    condition1 (np.ndarray): The first boolean condition.
    condition2 (np.ndarray): The second boolean condition.

    Returns:
    np.ndarray: An array of elements where both conditions are satisfied.
    """
    return arr[condition1 & condition2]

# Example usage
arr = np.array([1, 4, 6, 8, 3, 7, 2])
condition1 = arr > 3
condition2 = arr < 8

result = filter_elements(arr, condition1, condition2)
print(result)


[4 6 7]


Q. 34  Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [36]:
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extract elements from a 2D array using row and column indices provided in separate arrays.

    Parameters:
    arr (np.ndarray): The 2D array to extract elements from.
    row_indices (np.ndarray): The array of row indices.
    col_indices (np.ndarray): The array of column indices.

    Returns:
    np.ndarray: An array of extracted elements.
    """
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = extract_elements_2d(arr, row_indices, col_indices)
print(result)


[2 6 7]


Q. 36  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

In [37]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Adding a scalar value of 5 to each element
result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Q. 37  Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [38]:
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

# Broadcasting arr1 to match the shape of arr2 and performing element-wise multiplication
result = arr2 * arr1.T

print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


Q.38  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [39]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

# Adding arr1 to each row of arr2 using broadcasting
result = arr2 + arr1.T

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


Q. 39  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [40]:
import numpy as np

arr1 = np.array([[1],
                 [2],
                 [3]])

arr2 = np.array([[4, 5, 6]])

# Adding arr1 and arr2 using broadcasting
result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


Q. 40  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

# Reshape arr2 to make it compatible for broadcasting
arr2_reshaped = arr2[:, np.newaxis]

# Perform element-wise multiplication using broadcasting
result = arr1 * arr2_reshaped

print(result)

[[ 7 14 21]
 [36 45 54]]


 Q. 41 Calculate column wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)

print(column_mean)


[2.5 3.5 4.5]


Q. 42 Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])

In [43]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)

print(row_max)


[3 6]


Q. 43 For the given array, find indices of maximum value in each column. arr = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
column_max_indices = np.argmax(arr, axis=0)

print(column_max_indices)


[1 1 1]


Q. 44 For the given array, apply custom function to calculate moving sum along rows. arr = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
import numpy as np

def moving_sum(arr, window_size):
    """
    Calculate the moving sum along rows for a given array.

    Parameters:
    arr (np.ndarray): The input array.
    window_size (int): The size of the moving window.

    Returns:
    np.ndarray: An array with the moving sums.
    """
    result = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1] - window_size + 1):
            result[i, j + window_size - 1] = np.sum(arr[i, j:j + window_size])
    return result

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

window_size = 2
result = moving_sum(arr, window_size)
print(result)


[[ 0  3  5]
 [ 0  9 11]]


Q.45 . In the given array, check if all elements in each column are even.  arr = np.array([[2, 4, 6], [3, 5, 7]])

In [46]:
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
all_even = np.all(arr % 2 == 0, axis=0)

print(all_even)


[False False False]


Q.46 . Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])

In [47]:
import numpy as np

def reshape_array(original_array, m, n):
    """
    Reshape a 1D array into a matrix with dimensions m rows and n columns.

    Parameters:
    original_array (np.ndarray): The original 1D array.
    m (int): The number of rows.
    n (int): The number of columns.

    Returns:
    np.ndarray: The reshaped matrix.
    """
    return original_array.reshape(m, n)

# Example usage
original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3
reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


Q.47 Create a function that takes a matrix as input and returns the flattened array. input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
import numpy as np

def flatten_matrix(input_matrix):
    return input_matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


 Q.48 . Write a function that concatenates two given arrays along a specified axis  array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [49]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis0)

# Concatenate along axis 1 (columns)
concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


Q.49 Create a function that splits an array into multiple sub-arrays along a specified axis.   original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [50]:
import numpy as np

def split_array(original_array, indices_or_sections, axis=0):
    return np.split(original_array, indices_or_sections, axis=axis)

# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split into 3 sub-arrays along axis 0 (rows)
split_arrays_axis0 = split_array(original_array, 3, axis=0)
print("Split along axis 0:")
for sub_array in split_arrays_axis0:
    print(sub_array)

# Split into 3 sub-arrays along axis 1 (columns)
split_arrays_axis1 = split_array(original_array, 3, axis=1)
print("Split along axis 1:")
for sub_array in split_arrays_axis1:
    print(sub_array)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


Q.50  Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [51]:
import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)

    # Adjust indices to delete after insertion
    adjusted_indices_to_delete = [index + sum(i < index for i in indices_to_insert) for index in indices_to_delete]

    # Delete elements at specified indices
    modified_array = np.delete(modified_array, adjusted_indices_to_delete)

    return modified_array

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10  3 11  5]


Q.51  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [52]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 11, size=10)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result_array = arr1 + arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result_array)


arr1: [ 2  7  8  8  9  2  6 10  9 10]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise addition: [ 3  9 11 12 14  8 13 18 18 20]


Q.52  Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [53]:
import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result_array = arr1 - arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise subtraction:", result_array)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


Q.53  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [54]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 11, size=5)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result_array = arr1 * arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise multiplication:", result_array)


arr1: [5 4 1 4 6]
arr2: [1 2 3 4 5]
Result of element-wise multiplication: [ 5  8  3 16 30]


Q.54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [55]:
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result_array = arr1 / arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise division:", result_array)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


Q.55  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [56]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Calculate the exponentiation element-wise
result_array = np.power(arr1, arr2)

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result_array)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


Q.56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [57]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Use vectorized operation to count occurrences of the substring in each element
    count = np.char.count(arr, substring)
    # Sum the counts to get the total occurrences
    total_count = np.sum(count)
    return total_count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' occurs {occurrences} times in the array.")


The substring 'hello' occurs 3 times in the array.


Q.57 Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

def extract_uppercase(arr):
    # Use vectorized operation to extract uppercase characters from each element
    uppercase_chars = np.char.join('', np.char.findall(arr, r'[A-Z]'))
    return uppercase_chars

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)
print("Uppercase characters:", uppercase_characters)


Uppercase characters: ['H' 'W' 'OAI' 'GPT']


Q.58  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [59]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use vectorized operation to replace occurrences of the old substring with the new substring
    replaced_array = np.char.replace(arr, old_substring, new_substring)
    return replaced_array

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'
replaced_array = replace_substring(arr, old_substring, new_substring)
print("Replaced array:", replaced_array)


Replaced array: ['fruit' 'banana' 'grape' 'pinefruit']


Q. 59 Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [60]:
import numpy as np

def concatenate_strings(arr1, arr2):
    # Use vectorized operation to concatenate strings element-wise
    concatenated_array = np.char.add(arr1, arr2)
    return concatenated_array

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result_array = concatenate_strings(arr1, arr2)
print("Concatenated array:", result_array)


Concatenated array: ['HelloOpen' 'WorldAI']


Q. 60  Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])



In [61]:
import numpy as np

def longest_string_length(arr):
    # Use vectorized operation to find the length of each string
    lengths = np.vectorize(len)(arr)
    # Find the maximum length
    max_length = np.max(lengths)
    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max_length = longest_string_length(arr)
print("Length of the longest string:", max_length)


Length of the longest string: 9


Q. 61  Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [62]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(dataset)

# Compute the median
median = np.median(dataset)

# Compute the variance
variance = np.var(dataset)

# Compute the standard deviation
std_deviation = np.std(dataset)

# Print the results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [ 848  432  449  851  100  985  178  756  798  660  148  911  424  289
  962  266  698  640  545  544  715  245  152  676  511  460  883  184
   29  803  129  129  933   54  902  551  489  757  274  336  389  618
   43  443  544  889  258  322 1000  938   58  292  871  120  780  431
   83   92  897  399  612  566  909  634  939   85  204  325  775  965
   48  640  132  973  869  181  847  144  661  228  955  792  720  910
  374  854  561  306  582  170  676  449   96  198  607  257  882  691
  293  931]
Mean: 522.04
Median: 544.5
Variance: 91085.2984
Standard Deviation: 301.80341018616735


Q. 62  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [63]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
random_numbers = np.random.randint(1, 101, size=50)

# Find the 25th percentile
percentile_25 = np.percentile(random_numbers, 25)

# Find the 75th percentile
percentile_75 = np.percentile(random_numbers, 75)

# Print the results
print("Random numbers:", random_numbers)
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


Random numbers: [ 49  94   4  99  43  78  22  74   1  11  44  59  24  60   3  99  63  36
  95  68  83  47 100  21  82  51  28  15  42  59  66  37  11  87  44  12
   3  52  81  33  55   1  39  20  47  43  57  61  78  31]
25th percentile: 25.0
75th percentile: 67.5


Q. 63  Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [64]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.random.randint(1, 101, size=50)
array2 = np.random.randint(1, 101, size=50)

# Compute the correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)

# Print the arrays and the correlation coefficient matrix
print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation coefficient matrix:\n", correlation_matrix)


Array 1: [25  3  4 95 99 14 41 73 20 96 73 27 67 53 68 62 15 97  5 68 12 87 78 76
 57 17 25 30 22 26 81 61 62 84 34 33 71 86 32 14 72 57 25 80 42 19 41 55
 80 12]
Array 2: [39 94  2 96 45 89 25 68 83  4 77 36 87 62 70 88 44 33 12 85 11 55 38 29
  3 28 84 90 24 54 52 47 21 54 30 68 36 40 10 74 42 24  4 47 91 51  4 32
 10 11]
Correlation coefficient matrix:
 [[1.         0.06282198]
 [0.06282198 1.        ]]


Q. 64  Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [65]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result_matrix = np.dot(matrix1, matrix2)

# Print the matrices and the result
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of matrix multiplication:\n", result_matrix)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of matrix multiplication:
 [[ 58  64]
 [139 154]]


Q.65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [66]:
import numpy as np

# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1001, size=50)

# Calculate the 10th percentile
percentile_10 = np.percentile(array, 10)

# Calculate the 50th percentile (median)
percentile_50 = np.percentile(array, 50)

# Calculate the 90th percentile
percentile_90 = np.percentile(array, 90)

# Calculate the first quartile (25th percentile)
first_quartile = np.percentile(array, 25)

# Calculate the third quartile (75th percentile)
third_quartile = np.percentile(array, 75)

# Print the results
print("Array:", array)
print("10th percentile:", percentile_10)
print("50th percentile (median):", percentile_50)
print("90th percentile:", percentile_90)
print("First quartile (25th percentile):", first_quartile)
print("Third quartile (75th percentile):", third_quartile)


Array: [549 439 209 433  71 351 875  54 812 940  98  43 655 242 777  46 778 469
 300 207 904 959 264  90 456 146 199 139 219 378 301 386 357 178 894 814
 186 547 333 881 518 813 124 808  39 763 299 156 283 231]
10th percentile: 88.10000000000001
50th percentile (median): 342.0
90th percentile: 875.6
First quartile (25th percentile): 189.25
Third quartile (75th percentile): 736.0


Q. 66  Create a NumPy array of integers and find the index of a specific element.

In [67]:
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify the element to find
element_to_find = 50

# Find the index of the specific element
index = np.where(array == element_to_find)[0][0]

# Print the array and the index of the element
print("Array:", array)
print(f"Index of element {element_to_find}:", index)


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50: 4


Q.67 Generate a random NumPy array and sort it in ascending order.

In [68]:
import numpy as np

# Generate a random NumPy array
random_array = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Print the original and sorted arrays
print("Original array:", random_array)
print("Sorted array:", sorted_array)


Original array: [85  3 70 13 45 67 92 86 40 40]
Sorted array: [ 3 13 40 40 45 67 70 85 86 92]


Q.68 Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

In [69]:
import numpy as np

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

# Print the filtered array
print("Filtered array:", filtered_array)


Filtered array: [25 42 30]


Q.68 Filter elements which are divisible by 3 from a given NumPy array arr = np.array([1, 5, 8, 12, 15])

In [70]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]

print(filtered_arr)


[12 15]


Q.69 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. arr = np.array([10, 20, 30, 40, 50])

In [71]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print(filtered_arr)


[20 30 40]


Q.70 For the given NumPy array, check its byte order using the `dtype` attribute byteorder.  arr = np.array([1, 2, 3])

In [72]:
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print(byte_order)


=


Q.71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder. arr = np.array([1, 2, 3])

In [73]:
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print(byte_order)


=


Q.74 . For the given NumPy array, perform byte swapping in place using `byteswap()`. arr = np.array([1, 2, 3], dtype=np.int32)

In [74]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

print(arr)


[16777216 33554432 50331648]


Q.75 . For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`. arr = np.array([1, 2, 3], dtype=np.int32)

In [75]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print(swapped_arr)


[16777216 33554432 50331648]


Q.76  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [76]:
import numpy as np

# Create the original array
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a copy of the original array
copy_arr = arr1.copy()

# Modify an element in the copy
copy_arr[0] = 99

# Print both arrays to check if the original array is affected
print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [99  2  3  4  5  6  7  8  9 10]


Q.77  Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [77]:
import numpy as np

# Create a 2D array with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Extract a slice from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in the slice
view_slice[0, 0] = 999

# Print the original matrix and the slice to observe changes
print("Original matrix:\n", matrix)
print("Modified slice:\n", view_slice)


Original matrix:
 [[ 76  23  31]
 [ 18 999  72]
 [ 19  93  44]]
Modified slice:
 [[999  72]
 [ 93  44]]


Q.78  Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


In [78]:
import numpy as np

# Create the array with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice from the array
view_b = array_a[1:3, 1:3]

# Broadcast the addition of 5 to the slice
view_b += 5

# Print the original array and the slice to observe changes
print("Original array after modification:\n", array_a)
print("Modified slice:\n", view_b)


Original array after modification:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]
Modified slice:
 [[10 11]
 [13 14]]


Q.79 . Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [79]:
import numpy as np

# Create the original array with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 99

# Print the original array and the reshaped view to observe changes
print("Original array after modification:\n", orig_array)
print("Reshaped view:\n", reshaped_view)


Original array after modification:
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


Q.80  Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


In [80]:
import numpy as np

# Create a 2D array with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in the copy
if data_copy.size > 0:
    data_copy[0] = 99

# Print the original array and the copy to observe changes
print("Original array:\n", data)
print("Modified copy:\n", data_copy)


Original array:
 [[4 2 6 3]
 [1 2 1 7]
 [1 5 9 5]]
Modified copy:
 [99  7  9]


Q.81  Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [81]:
import numpy as np

# Create two matrices A and B of shape (3, 3) with random integers
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

# Print the matrices and the results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition of A and B:\n", addition_result)
print("Subtraction of A and B:\n", subtraction_result)


Matrix A:
 [[4 4 9]
 [9 8 1]
 [4 9 8]]
Matrix B:
 [[8 2 9]
 [5 8 1]
 [5 1 7]]
Addition of A and B:
 [[12  6 18]
 [14 16  2]
 [ 9 10 15]]
Subtraction of A and B:
 [[-4  2  0]
 [ 4  0  0]
 [-1  8  1]]


Q.82  Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [82]:
import numpy as np

# Generate matrix C of shape (3, 2) with random integers
C = np.random.randint(1, 10, size=(3, 2))

# Generate matrix D of shape (2, 4) with random integers
D = np.random.randint(1, 10, size=(2, 4))

# Perform matrix multiplication
result = np.dot(C, D)

# Print the matrices and the result
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication result (C * D):\n", result)


Matrix C:
 [[5 3]
 [5 7]
 [4 4]]
Matrix D:
 [[8 9 6 1]
 [9 6 5 8]]
Matrix multiplication result (C * D):
 [[ 67  63  45  29]
 [103  87  65  61]
 [ 68  60  44  36]]


Q.83 Create a matrix `E` and find its transpose.

In [83]:
import numpy as np

# Create a matrix E of shape (3, 3) with random integers
E = np.random.randint(1, 10, size=(3, 3))

# Find the transpose of the matrix
transpose_E = E.T

# Print the original matrix and its transpose
print("Matrix E:\n", E)
print("Transpose of E:\n", transpose_E)


Matrix E:
 [[5 2 4]
 [4 3 6]
 [3 4 6]]
Transpose of E:
 [[5 4 3]
 [2 3 4]
 [4 6 6]]


Q.84 Generate a square matrix `F` and compute its determinant.

In [84]:
import numpy as np

# Generate a square matrix F of shape (3, 3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of the matrix
determinant_F = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F:\n", F)
print("Determinant of F:", determinant_F)


Matrix F:
 [[8 3 8]
 [2 7 6]
 [1 1 4]]
Determinant of F: 129.99999999999997


Q.85 Create a square matrix `G` and find its inverse.

In [85]:
import numpy as np

# Create a square matrix G of shape (3, 3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Compute the inverse of the matrix
inverse_G = np.linalg.inv(G)

# Print the matrix and its inverse
print("Matrix G:\n", G)
print("Inverse of G:\n", inverse_G)


Matrix G:
 [[2 7 7]
 [8 9 9]
 [8 1 9]]
Inverse of G:
 [[-0.23684211  0.18421053  0.        ]
 [-0.          0.125      -0.125     ]
 [ 0.21052632 -0.17763158  0.125     ]]
